In [1]:
from src.environments import *
from src.agents import *

In [2]:
env   = MultiArmedBandit.default()
agent = KDEAgent.default()

In [3]:
env.play_episode(100, agent)

In [4]:
R_mat, D_mat = agent.sample_R_and_D_matrices(10)

In [6]:
P_R = np.einsum('ijk, ijk -> ij', D_mat[0,:,:,:], np.expand_dims(R_mat[0,:,:], -1))

In [7]:
P_R

array([[-1.29511086, 13.15198106, 10.56079156]])

In [8]:
P = np.array([[[0.1, 0.2], [0.9, 0.8]], [[0.3, 0.8], [0.7, 0.2]]])

In [10]:
P.shape

(2, 2, 2)

In [11]:
P

array([[[0.1, 0.2],
        [0.9, 0.8]],

       [[0.3, 0.8],
        [0.7, 0.2]]])

In [12]:
pi = np.array([[1, 0], [0, 1]])

In [23]:
M = np.einsum('ijk,jl->ikl', P, pi)

new_M = np.array(M[0,0,:], M[1,])

array([0.1, 0.9])

In [24]:
M = np.einsum('ijk,jl->ikl', P, pi)

In [26]:
M[0,0,:]

array([0.1, 0.9])

In [38]:
np.einsum('ijk->jk', np.einsum('ijk,jl->ikl', P, pi), pi)

ValueError: einstein sum subscripts string includes output subscript 'i' multiple times

In [34]:
np.einsum('ijk,jl->ikl->', P, pi)

array([[0.1, 0.8],
       [0.3, 0.2]])