In [1]:
from src.environments import *
from src.agents import *

In [2]:
env   = MultiArmedBandit.default()
agent = BayesianAgent.default()

In [13]:
env.play_episode(1000, agent)

change!
change!
change!
change!
change!
change!


In [14]:
Q, u = agent.get_monte_carlo_Q(10)

In [15]:
Q, u

(array([[18.90984374, 19.73932444, 20.91181549]]),
 array([[0.09215515, 0.1690312 , 0.09090731]]))

In [19]:
[pair[1] for pair in agent._sa_pairs if pair[0] == 1]

[]

In [7]:
D  = agent.get_moment_dynamics_matrix(which_moment = 1)
R  = agent.get_moment_rewards_matrix(which_moment = 1)
R2 = agent.get_moment_rewards_matrix(which_moment = 2)

In [9]:
np.sqrt(R2 - R**2)

array([[1.01524175, 2.01668189, 0.4946324 ]])

In [19]:
from scipy.stats import norm

x = [10, np.sqrt(5)]
y = [8, np.sqrt(1500000000)]

norm.cdf((x[0] - y[0])/np.sqrt((x[1]**2 + y[1]**2)))

0.5000206012907311

In [318]:
a1 = [10, 0.00001**2]
a2 = [5, 7**2]
a3 = [8, 1**2]

e_1 = a1[0] + np.sqrt(a1[1])*norm.pdf((a1[0] - a1[0])/np.sqrt(a1[1]))/(1-norm.cdf((a1[0] - a1[0])/np.sqrt(a1[1])))
e_2 = a2[0] + np.sqrt(a2[1])*norm.pdf((a1[0] - a2[0])/np.sqrt(a2[1]))/(1-norm.cdf((a1[0] - a2[0])/np.sqrt(a2[1])))
e_3 = a3[0] + np.sqrt(a3[1])*norm.pdf((a1[0] - a3[0])/np.sqrt(a3[1]))/(1-norm.cdf((a1[0] - a3[0])/np.sqrt(a3[1])))

p_1 = 1-norm.cdf((a1[0]-a1[0])/np.sqrt(a1[1]))
p_2 = 1-norm.cdf((a1[0]-a2[0])/np.sqrt(a2[1]))
p_3 = 1-norm.cdf((a1[0]-a3[0])/np.sqrt(a3[1]))

In [319]:
print(e_1, e_2, e_3, p_1, p_2, p_3)

10.000007978845607 14.109801026080813 10.37321553282284 0.5 0.23752526202697655 0.02275013194817921


In [320]:
print('Scheme 1')
print('Potential value of taking action weighed by probability of success')
print(e_1*p_1, e_2*p_2, e_3*p_3)

print('Potential loss of taking action weighed by probability of failure')
print((a1[0]-a1[0])*(1-p_1), (a1[0]-a2[0])*(1-p_2), (a1[0]-a3[0])*(1-p_3))

print('Is is worth to take this action?')
print(e_1*p_1 > (a1[0]-a1[0])*(1-p_1), e_2*p_2 > (a1[0]-a2[0])*(1-p_2), e_3*p_3 > (a1[0]-a3[0])*(1-p_3))

Scheme 1
Potential value of taking action weighed by probability of success
5.000003989422804 3.3514341858683476 0.23599202209862172
Potential loss of taking action weighed by probability of failure
0.0 3.812373689865117 1.9544997361036416
Is is worth to take this action?
True False False


In [314]:
print('Scheme 2')
print('a2>a1 = ', norm.cdf((a2[0] - a1[0])/np.sqrt((a2[1]**2 + a1[1]**2))))
print('a3>a1 = ', norm.cdf((a3[0] - a1[0])/np.sqrt((a3[1]**2 + a1[1]**2))))

Scheme 2
a2>a1 =  0.4593621387038567
a3>a1 =  0.0


In [324]:
from scipy.stats import entropy

print(entropy([0.1, 0.5, 0.2, 0.2]))

print(entropy([0.01, 0.85, 0.05, 0.09]))

print(entropy([0.25, 0.25, 0.25, 0.25]))

print(entropy([1, 0, 0, 0]))

1.2206072645530175
0.5506945103893577
1.3862943611198906
0.0


In [230]:
print('Value of information in q units')
print(e_1-a1[0], e_2-a1[0], e_3-a1[0])

Value of information in q units
0.0007978845608036522 0.35268075098577967 0.2444561927113078


In [231]:
print('Value of information in q units weighed by probability')
print(p_1*(e_1-a1[0]), p_2*(e_2-a1[0]), p_3*(e_3-a1[0]))

Value of information in q units weighed by probability
0.0003989422804018261 7.176207156384138e-05 0.0012006801430331073


In [140]:
print(p_1/(p_1+p_2+p_3), p_2/(p_1+p_2+p_3), p_3/(p_1+p_2+p_3))

0.6094084542387069 0.06937889648903672 0.32121264927225635


In [141]:
print(e_1*p_1, e_2*p_2, e_3*p_3)

5.126156626101008 0.646060530353008 3.141240122396709


In [327]:
from scipy import stats
num_samples = 10
tau = stats.gamma.rvs(a = 2, scale = 1/2, size=num_samples)

In [336]:
m = 100 + stats.norm.rvs(size = num_samples)*np.sqrt(1/(5*tau))

In [331]:
tau

array([0.80506246, 1.19220641, 0.38679645, 0.42332936, 0.96034694,
       1.15398577, 2.13803186, 0.72072044, 0.60088745, 1.95226129])

In [339]:
np.random.choice()

array([ 2,  6, 12, 20])